# Generated by Django 5.2.4 on 2025-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/notes/')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
